-- 직원관리 계정 생성
-- 계정명 : C##EMPLOYEE, 비밀번호 : EMPLOYEE로 새로운 계정 생성
CREATE USER C##EMPLOYEE IDENTIFIED BY EMPLOYEE;
-- C##EMPLOYEE 계정에 접속 권한, 테이블 생성 권한 등을 부여
GRANT RESOURCE, CONNECT TO C##EMPLOYEE;
-- C##EMPLOYEE 계정에 테이블 스페이스 부여
ALTER USER C##EMPLOYEE QUOTA UNLIMITED ON USERS;
-------------------------------------------------------
------ 과제 계정 생성
CREATE USER C##HOMEWORK IDENTIFIED BY HOMEWORK;
GRANT RESOURCE, CONNECT TO C##HOMEWORK;
ALTER USER C##HOMEWORK QUOTA UNLIMITED ON USERS;
---------- 파이널 과제 생성
CREATE USER C##FINAL IDENTIFIED BY FINAL;
GRANT RESOURCE, CONNECT TO C##FINAL;
ALTER USER C##FINAL QUOTA UNLIMITED ON USERS;